name: Learn Serverless Framework
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Transpile-into-TS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Install layer dependencies
        run: cd layers/nodejs && pnpm install --no-frozen-lockfile

      - name: transpile TS to JS
        run: pnpm tsc -p .

      - name: Deploy using serverless framework
        uses: serverless/github-action@v3.2
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLS_DEBUG: 1
